### ISSUE TITLE
error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'

### ISSUE THREAD

**Issue by ZhiXiao-Lin** [kyle-mccarthy/nest-next#21]
Hey!
  
Thank you for sharing the code. 
 I got an error when I upgraded the version of next to 9.0.

```
error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'
```

This should be due to the new feature zero-config typescript support of next 9.0.

Now, the absence of either declaration and isolatedModules will cause errors, and the two options conflict with each other.

Do you have similar problems? Is there a solution? 

Thanks!

**Comment by kyle-mccarthy** [comment]
Do you need this option set for your server side code?

**Comment by ZhiXiao-Lin** [comment]
> Do you need this option set for your server side code?

After I reinstalled the dependency, everything went well.
